/**
 * @file alfloaterlightbox.h
 * @brief A generic text floater for dumping info (usually debug info)
 *
 * Copyright (c) Rye Mutt <rye@alchemyviewer.org>
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#pragma once

#ifndef AL_FLOATERLIGHTBOX_H
#define AL_FLOATERLIGHTBOX_H

#include "llfloater.h"
#include <string>

class ALFloaterLightBox final : public LLFloater
{
public:
    ALFloaterLightBox(const LLSD& key);
    ~ALFloaterLightBox() override;
    bool postBuild() override;
    virtual void draw() override;

  private:
    void onClickResetControlDefault(const LLSD& userdata);
    void onClickResetGroupDefault(const LLSD& userdata);
    void updateTonemapper();
    void updateCAS();
    void populateLUTCombo();

    // [BDMerge G3.3 Batch 3] Selected Light quick panel: live per-projector
    // controls that follow the currently-selected object.
    void updateSelectedLightPanel();
    void onSelLightCastShadows();
    void onSelLightVolumetric();
    void onSelLightCaptureOverride();
    void onSelLightClearOverride();
    void onSelGoboChanged();

    // [Cine Haze] Depth Haze tab actions.
    void onCineHazePreset(const LLSD& userdata);
    void onCineHazeRefFromCamera();

    // [RotoInk] Roto Ink tab: "reset" (all controls to default) or an
    // ALRotoInk preset key.
    void onRotoInkPreset(const LLSD& userdata);
    // [RotoInk] Shows the Silhouette/Metric threshold row matching
    // CineOutlineDepthMode and hides the other (pattern: updateTonemapper()).
    void updateRotoInkDepthMode();
    // [RotoInk Anim] Single show/hide pass over every round-A control whose
    // visibility depends on another control's value (A.8): layer 1/2 motion
    // Shape/Angle/anchor-hint per style, the Tempo Phase row, the Pattern
    // group's per-type rows (and the Ratio label text), the secondary-colour
    // Speed/Length rows per colour mode, and the whole Subject "extras" set
    // per CineOutlineSubjectMode/TargetSet. Re-run on any of the six driving
    // settings changing (see the connections below) -- same
    // findChild+setVisible idiom as updateRotoInkDepthMode()/updateTonemapper().
    void updateRotoInkAnimVisibility();

    boost::signals2::scoped_connection mTonemapConnection;
    boost::signals2::scoped_connection mCASConnection;
    boost::signals2::scoped_connection mRotoInkDepthModeConnection;
    // [RotoInk Anim] All seven drive the same updateRotoInkAnimVisibility().
    boost::signals2::scoped_connection mRotoInkMotionStyleConnection;
    boost::signals2::scoped_connection mRotoInkMotion2StyleConnection;
    boost::signals2::scoped_connection mRotoInkMotionTempoConnection;
    boost::signals2::scoped_connection mRotoInkPatternTypeConnection;
    boost::signals2::scoped_connection mRotoInkColor2ModeConnection;
    boost::signals2::scoped_connection mRotoInkSubjectModeConnection;
    boost::signals2::scoped_connection mRotoInkSubjectTargetSetConnection;
    // [RotoInk UI] Gates the Ink group's Colour swatch (Fixed only) / Match
    // reach (Match only) rows -- see updateRotoInkAnimVisibility().
    boost::signals2::scoped_connection mRotoInkInkColorModeConnection;
    boost::signals2::scoped_connection mRotoInkBlendModeConnection; // [RotoInk UI] fallback-colour row
};

#endif // AL_FLOATERLIGHTBOX_H
