/**
 * @file alfloaterlightbox.cpp
 * @brief A generic text floater for dumping info (usually debug info)
 *
 * Copyright (C) Rye Mutt <rye@alchemyviewer.org>
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "llviewerprecompiledheaders.h"
#include "alfloaterlightbox.h"

#include "bdmergemeshpool.h"
#include "bdmergetexpool.h"
#include "llvoavatarself.h"

//#include "alrenderutils.h"
#include "llviewercontrol.h"
#include "llspinctrl.h"
#include "llsliderctrl.h"
#include "lltextbox.h"
#include "llcombobox.h"

ALFloaterLightBox::ALFloaterLightBox(const LLSD& key)
:   LLFloater(key)
{
    mCommitCallbackRegistrar.add("LightBox.ResetControlDefault", std::bind(&ALFloaterLightBox::onClickResetControlDefault, this, std::placeholders::_2));
    mCommitCallbackRegistrar.add("LightBox.ResetGroupDefault", std::bind(&ALFloaterLightBox::onClickResetGroupDefault, this, std::placeholders::_2));
}

ALFloaterLightBox::~ALFloaterLightBox()
{
    mTonemapConnection.disconnect();
    mCASConnection.disconnect();
}

bool ALFloaterLightBox::postBuild()
{
    populateLUTCombo();
    updateTonemapper();
    updateCAS();

    mTonemapConnection = gSavedSettings.getControl("AlchemyRenderTonemapType")->getSignal()->connect([&](LLControlVariable* control, const LLSD&, const LLSD&) { updateTonemapper(); });
    //mCASConnection = gSavedSettings.getControl("RenderSharpenMethod")->getSignal()->connect([&](LLControlVariable* control, const LLSD&, const LLSD&) { updateCAS(); });

    return LLFloater::postBuild();
}

void ALFloaterLightBox::draw()
{
    // [BDMerge B-2b.3] live RAM-pool readouts on the Machinima tab
    static LLFrameTimer pool_stats_timer;
    if (pool_stats_timer.getElapsedTimeF32() > 1.f)
    {
        pool_stats_timer.reset();

        // [BDMerge B6] BD Bone Camera joint dropdown - donor fill code
        // (BD 9682ff208e), populated lazily once the avatar skeleton exists
        LLComboBox* joint_combo = getChild<LLComboBox>("bd_joint_combo");
        if (joint_combo->getItemCount() <= 1 && isAgentAvatarValid())
        {
            S32 current = gSavedSettings.getS32("CameraFollowJoint");
            joint_combo->clear();
            joint_combo->add("None", -1);
            for (auto joint : gAgentAvatarp->getSkeleton())
            {
                if (joint)
                {
                    joint_combo->add(joint->getName(), joint->mJointNum);
                }
            }
            joint_combo->setSelectedByValue(current, true);
        }
        getChild<LLTextBox>("bd_texpool_stats")->setValue("Textures: " + BDMergeTexPool::shortStatus());
        getChild<LLTextBox>("bd_meshpool_stats")->setValue("Meshes: " + BDMergeMeshPool::shortStatus());
    }
    LLFloater::draw();
}

void ALFloaterLightBox::populateLUTCombo()
{
    LLComboBox* lut_combo = getChild<LLComboBox>("colorlut_combo");
    const std::string& user_luts = gDirUtilp->getExpandedFilename(LL_PATH_USER_SETTINGS, "colorlut");

    std::error_code ec;
    std::filesystem::path user_luts_path = fsyspath(user_luts);
    if(std::filesystem::is_directory(user_luts_path, ec))
    {
        if(ec)
        {
            LL_WARNS() << "Error checking user LUTs directory: " << ec.message() << LL_ENDL;
            return;
        }
        if(!std::filesystem::is_empty(user_luts_path, ec) && !ec)
        {
            if(ec)
            {
                LL_WARNS() << "Error checking contents of user LUTs directory: " << ec.message() << LL_ENDL;
                return;
            }
            lut_combo->addSeparator();
        }
        for (std::filesystem::directory_iterator lut(user_luts_path, ec); lut != std::filesystem::directory_iterator(); ++lut)
        {
            if(ec)
            {
                LL_WARNS() << "Error reading user LUT file: " << ec.message() << LL_ENDL;
                continue;
            }
#if LL_WINDOWS
            std::string lut_stem = ll_convert_wide_to_string(lut->path().stem().native());
            std::string lut_filename = ll_convert_wide_to_string(lut->path().filename().native());
#else
            std::string lut_stem = lut->path().stem().native();
            std::string lut_filename = lut->path().filename().native();
#endif
            lut_combo->add(lut_stem, lut_filename);
        }
        lut_combo->selectByValue(gSavedSettings.getString("RenderColorGradeLUT"));
        lut_combo->resetDirty();
    }
}

void ALFloaterLightBox::onClickResetControlDefault(const LLSD& userdata)
{
    const std::string& control_name = userdata.asString();
    LLControlVariable* controlp = gSavedSettings.getControl(control_name);
    if (controlp)
    {
        controlp->resetToDefault(true);
    }
}

void ALFloaterLightBox::onClickResetGroupDefault(const LLSD& userdata)
{
    const std::string& setting_group = userdata.asString();
    if (setting_group == "sharpen")
    {
        LLControlVariable* controlp = gSavedSettings.getControl("RenderSharpenMethod");
        if (controlp)
        {
            controlp->resetToDefault(true);
        }
        controlp = gSavedSettings.getControl("RenderSharpenCASSharpness");
        if (controlp)
        {
            controlp->resetToDefault(true);
        }
        controlp = gSavedSettings.getControl("RenderSharpenDLSSharpness");
        if (controlp)
        {
            controlp->resetToDefault(true);
        }
        controlp = gSavedSettings.getControl("RenderSharpenDLSDenoise");
        if (controlp)
        {
            controlp->resetToDefault(true);
        }
    }
    else if (setting_group == "tonemap")
    {
        {
            LLControlVariable* controlp = gSavedSettings.getControl("RenderExposure");
            if (controlp)
            {
                controlp->resetToDefault(true);
            }
        }

        // AMD FidelityFX LPM (tonemap type 7) parameters.
        static const char* const amd_lpm_controls[] = {
            "AlchemyToneMapAMDHDRMax",
            "AlchemyToneMapAMDExposure",
            "AlchemyToneMapAMDContrast",
            "AlchemyToneMapAMDSaturationR",
            "AlchemyToneMapAMDSaturationG",
            "AlchemyToneMapAMDSaturationB",
        };
        for (const char* control_name : amd_lpm_controls)
        {
            LLControlVariable* controlp = gSavedSettings.getControl(control_name);
            if (controlp)
            {
                controlp->resetToDefault(true);
            }
        }

        //S32 tone_map_type = gSavedSettings.getS32("AlchemyRenderTonemapType");
        //switch (tone_map_type)
        //{
        //case ALRenderUtil::TONEMAP_AMD:
        //{
        //    LLControlVariable* controlp = gSavedSettings.getControl("AlchemyToneMapAMDHDRMax");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapAMDExposure");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapAMDContrast");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapAMDSaturationR");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapAMDSaturationG");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapAMDSaturationB");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    break;
        //}
        //case ALRenderUtil::TONEMAP_UCHIMURA:
        //{
        //    LLControlVariable* controlp = gSavedSettings.getControl("AlchemyToneMapUchimuraMaxBrightness");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapUchimuraContrast");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapUchimuraLinearStart");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapUchimuraLinearLength");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapUchimuraBlackLevel");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    break;
        //}
        //case ALRenderUtil::TONEMAP_UNCHARTED:
        //{
        //    LLControlVariable* controlp = gSavedSettings.getControl("AlchemyToneMapFilmicToeStr");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapFilmicToeLen");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapFilmicShoulderStr");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapFilmicShoulderLen");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapFilmicShoulderAngle");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapFilmicGamma");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    controlp = gSavedSettings.getControl("AlchemyToneMapFilmicWhitePoint");
        //    if (controlp)
        //    {
        //        controlp->resetToDefault(true);
        //    }
        //    break;
        //}
        //}
    }
}

void ALFloaterLightBox::updateTonemapper()
{
    // [AMD LPM] The AMD LPM parameter sliders live in the Image tab but only
    // affect tonemap type 7; show them only when AMD LPM is selected and hide
    // them for every other tonemapper. (findChild avoids dummy-widget spam.)
    static const std::string amd_widgets[] = {
        "lpm_hdrmax_label",   "lpm_hdrmax_slider",   "lpm_hdrmax_spinner",
        "lpm_toneexp_label",  "lpm_toneexp_slider",  "lpm_toneexp_spinner",
        "lpm_contrast_label", "lpm_contrast_slider", "lpm_contrast_spinner",
        "lpm_satr_label",     "lpm_satr_slider",     "lpm_satr_spinner",
        "lpm_satg_label",     "lpm_satg_slider",     "lpm_satg_spinner",
        "lpm_satb_label",     "lpm_satb_slider",     "lpm_satb_spinner",
    };
    const bool amd = (gSavedSettings.getS32("AlchemyRenderTonemapType") == 7);
    for (const std::string& widget_name : amd_widgets)
    {
        if (LLView* v = findChild<LLView>(widget_name))
        {
            v->setVisible(amd);
        }
    }
}

void ALFloaterLightBox::updateCAS()
{
    // Init UI
    LLTextBox* text2 = getChild<LLTextBox>("sharp_dynamic_text");
    LLSpinCtrl* spinner1 = getChild<LLSpinCtrl>("sharp_strength_spinner");
    LLSpinCtrl* spinner2 = getChild<LLSpinCtrl>("sharp_dynamic_spinner");
    LLSliderCtrl* slider1 = getChild<LLSliderCtrl>("sharp_strength_slider");
    LLSliderCtrl* slider2 = getChild<LLSliderCtrl>("sharp_dynamic_slider");

    //switch (gSavedSettings.getU32("RenderSharpenMethod"))
    //{
    //default:
    //case ALRenderUtil::SHARPEN_NONE:
    //{
    //    spinner1->setVisible(false);
    //    slider1->setVisible(false);
    //    text2->setVisible(false);
    //    spinner2->setVisible(false);
    //    slider2->setVisible(false);
    //    break;
    //}
    //case ALRenderUtil::SHARPEN_CAS:
    //{
    //    spinner1->setVisible(true);
    //    spinner1->setMinValue(0.0f);
    //    spinner1->setMaxValue(1.0f);
    //    spinner1->setIncrement(0.1f);
    //    spinner1->setControlName("RenderSharpenCASSharpness");
    //    slider1->setVisible(true);
    //    slider1->setMinValue(0.0f);
    //    slider1->setMaxValue(1.0f);
    //    slider1->setIncrement(0.1f);
    //    slider1->setControlName("RenderSharpenCASSharpness", nullptr);

    //    text2->setVisible(false);
    //    spinner2->setVisible(false);
    //    slider2->setVisible(false);
    //    break;
    //}
    //case ALRenderUtil::SHARPEN_DLS:
    //{
    //    spinner1->setVisible(true);
    //    spinner1->setMinValue(0.0f);
    //    spinner1->setMaxValue(1.0f);
    //    spinner1->setIncrement(0.1f);
    //    spinner1->setControlName("RenderSharpenDLSSharpness");
    //    slider1->setVisible(true);
    //    slider1->setMinValue(0.0f);
    //    slider1->setMaxValue(1.0f);
    //    slider1->setIncrement(0.1f);
    //    slider1->setControlName("RenderSharpenDLSSharpness", nullptr);

    //    text2->setVisible(true);
    //    text2->setText(std::string("Denoise:"));
    //    spinner2->setVisible(true);
    //    spinner2->setMinValue(0.0f);
    //    spinner2->setMaxValue(1.0f);
    //    spinner2->setIncrement(0.1f);
    //    spinner2->setControlName("RenderSharpenDLSDenoise");
    //    slider2->setVisible(true);
    //    slider2->setMinValue(0.0f);
    //    slider2->setMaxValue(1.0f);
    //    slider2->setIncrement(0.1f);
    //    slider2->setControlName("RenderSharpenDLSDenoise", nullptr);
    //    break;
    //}
    //}
}
