/**
 * @file alfloaterlightbox.h
 * @brief A generic text floater for dumping info (usually debug info)
 *
 * Copyright (c) Rye Mutt <rye@alchemyviewer.org>
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#pragma once

#ifndef AL_FLOATERLIGHTBOX_H
#define AL_FLOATERLIGHTBOX_H

#include "llfloater.h"
#include <string>

class ALFloaterLightBox final : public LLFloater
{
public:
    ALFloaterLightBox(const LLSD& key);
    ~ALFloaterLightBox() override;
    bool postBuild() override;
    virtual void draw() override;

  private:
    void onClickResetControlDefault(const LLSD& userdata);
    void onClickResetGroupDefault(const LLSD& userdata);
    void updateTonemapper();
    void updateCAS();
    void populateLUTCombo();

    // [BDMerge G3.3 Batch 3] Selected Light quick panel: live per-projector
    // controls that follow the currently-selected object.
    void updateSelectedLightPanel();
    void onSelLightCastShadows();
    void onSelLightVolumetric();
    void onSelLightCaptureOverride();
    void onSelLightClearOverride();
    void onSelGoboChanged();

    // [Cine Haze] Depth Haze tab actions.
    void onCineHazePreset(const LLSD& userdata);
    void onCineHazeRefFromCamera();

    // [RotoInk] Roto Ink tab: "reset" (all controls to default) or an
    // ALRotoInk preset key.
    void onRotoInkPreset(const LLSD& userdata);
    // [RotoInk] Shows the Silhouette/Metric threshold row matching
    // CineOutlineDepthMode and hides the other (pattern: updateTonemapper()).
    void updateRotoInkDepthMode();

    // [TronT1] Tron tab: "reset" (all controls to default) or an ALTron
    // look-preset key (tr_preset_combo is wired directly in postBuild, same
    // action-combo idiom as ri_preset_combo; this registrar entry only ever
    // receives "reset" from tr_reset_all).
    void onTronPreset(const LLSD& userdata);
    // [TronT1] tr_palette_combo commit: writes the four colour swatches for
    // the selected named palette (id 0 Custom is a no-op, matching
    // ALTron::applyPalettePreset's own contract).
    void onTronPaletteSelected();
    // [TronT1] Any of the four tr_color_* swatches: sets TronPalette back to
    // 0 (Custom) so the palette combo doesn't silently disagree with a
    // hand-edited swatch.
    void onTronColorEdited();
    // [TronT1] tr_grid_origin_snap_btn / tr_grid_origin_clear_btn.
    void onTronGridOriginSnap();
    void onTronGridOriginClear();
    // [TronT1] Integration group buttons: apply the Roto Ink / Rig Rim
    // preset linked to the most recently applied Tron look preset (see
    // ALTron::lastPresetRotoKey()/lastPresetRigRimLabel()), even if the
    // matching "+ Roto Ink"/"+ Rig Rim" checkbox was off when it was applied.
    void onTronApplyRotoPreset();
    void onTronApplyRigRimPreset();
    // [TronT1] Single show/hide pass over every Tron tab control whose
    // visibility depends on another control's value (mirrors
    // updateRotoInkAnimVisibility()'s shape): the Scene-layer hint under the
    // Layer combo, every Grade row but Strength when Strength == 0, every
    // Grid row (incl. the Pulses sub-rows, further gated on Pulse amount ==
    // 0) when Grid Enable is off, the single-subject target row per Target
    // set, the whole Subject group per the grid-exclude/radius/keep-subject
    // OR, and the tag-unavailable hint under the mask-source combos.
    void updateTronVisibility();
    // [RotoInk Anim] Single show/hide pass over every round-A control whose
    // visibility depends on another control's value (A.8): layer 1/2 motion
    // Shape/Angle/anchor-hint per style, the Tempo Phase row, the Pattern
    // group's per-type rows (and the Ratio label text), the secondary-colour
    // Speed/Length rows per colour mode, and the whole Subject "extras" set
    // per CineOutlineSubjectMode/TargetSet. Re-run on any of the six driving
    // settings changing (see the connections below) -- same
    // findChild+setVisible idiom as updateRotoInkDepthMode()/updateTonemapper().
    void updateRotoInkAnimVisibility();

    boost::signals2::scoped_connection mTonemapConnection;
    boost::signals2::scoped_connection mCASConnection;
    boost::signals2::scoped_connection mRotoInkDepthModeConnection;
    // [TronT1] Every driver of updateTronVisibility().
    boost::signals2::scoped_connection mTronLayerConnection;
    boost::signals2::scoped_connection mTronGradeStrengthConnection;
    boost::signals2::scoped_connection mTronGridEnabledConnection;
    boost::signals2::scoped_connection mTronPulseGridAmountConnection;
    boost::signals2::scoped_connection mTronGridSubjectExcludeConnection;
    boost::signals2::scoped_connection mTronGridSubjectRadiusConnection;
    boost::signals2::scoped_connection mTronGradeKeepSubjectConnection;
    boost::signals2::scoped_connection mTronSubjectTargetSetConnection;
    // [RotoInk Anim] All seven drive the same updateRotoInkAnimVisibility().
    boost::signals2::scoped_connection mRotoInkMotionStyleConnection;
    boost::signals2::scoped_connection mRotoInkMotion2StyleConnection;
    boost::signals2::scoped_connection mRotoInkMotionTempoConnection;
    boost::signals2::scoped_connection mRotoInkPatternTypeConnection;
    boost::signals2::scoped_connection mRotoInkColor2ModeConnection;
    boost::signals2::scoped_connection mRotoInkSubjectModeConnection;
    boost::signals2::scoped_connection mRotoInkSubjectTargetSetConnection;
    // [RotoInk UI] Gates the Ink group's Colour swatch (Fixed only) / Match
    // reach (Match only) rows -- see updateRotoInkAnimVisibility().
    boost::signals2::scoped_connection mRotoInkInkColorModeConnection;
    boost::signals2::scoped_connection mRotoInkBlendModeConnection; // [RotoInk UI] fallback-colour row
};

#endif // AL_FLOATERLIGHTBOX_H
