/**
 * @file aldiopterrelevance_test.cpp
 * @brief Three-layer validation of the Ultimate Diopter relevance model
 *        (design doc DIOPTER_SMART_UI_DESIGN.md section 2.3).
 *
 * Layer 1 (test<2>) -- structural: every mCtrlName / mResetName resolves
 * against floater_ultimate_diopter.xml (parsed textually, not instantiated);
 * all 181 CineDiopter* settings appear exactly once; mPresetOwned matches
 * the canonical 44 + 49 owned lists; count bounds; exactly one nullptr
 * reset and one UNCONDITIONAL row (both diopter_enabled);
 * mClauseCount == 0 iff mUnconditional.
 *
 * Layer 2 (test<1>) -- cross-product branch coverage: the S0-S8 sweep corpus
 * (1580 states) asserts, per state, that the table's relevant-set equals the
 * consumed-set recombined from the committed oracle
 * (aldiopterrelevance_oracle.llsd, regenerated by
 * aldiopterrelevance_oracle.py), then asserts the corpus's own adequacy:
 * every predicate observed in both states, every clause observed passing and
 * failing, every non-UNCONDITIONAL row observed relevant and irrelevant.
 *
 * Layer 3 (runtime differential, debug builds) lives with the renderer, not
 * here -- see the design doc.
 *
 * $LicenseInfo:firstyear=2026&license=viewerlgpl$
 * Alchemy-Machinima fork
 * $/LicenseInfo$
 */

#include "linden_common.h"

#include "../test/lltut.h"
#include "../aldiopterrelevance.h"

#include "llsd.h"
#include "llsdserialize.h"
#include "llstring.h"

#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace
{
    // ---------------------------------------------------------------------
    // Source-tree files, located relative to this source file so the test
    // is independent of the harness working directory.
    // ---------------------------------------------------------------------

    std::string testsDir()
    {
        std::string self(__FILE__);
        std::string::size_type slash = self.find_last_of("/\\");
        return (slash == std::string::npos) ? std::string(".")
                                            : self.substr(0, slash);
    }

    std::string readFileOrFail(const std::string& path)
    {
        std::ifstream in(path.c_str(), std::ios::in | std::ios::binary);
        tut::ensure("readable: " + path, in.good());
        std::ostringstream buf;
        buf << in.rdbuf();
        return buf.str();
    }

    std::string floaterXmlPath()
    {
        return testsDir() +
               "/../skins/default/xui/en/floater_ultimate_diopter.xml";
    }

    std::string oracleLlsdPath()
    {
        return testsDir() + "/aldiopterrelevance_oracle.llsd";
    }

    // ---------------------------------------------------------------------
    // Textual XUI scan (Layer 1).  The floater is parsed as text -- element
    // spans and attributes -- never instantiated, so no LLUI is involved.
    // ---------------------------------------------------------------------

    // Attribute lookup that respects token boundaries, so a search for
    // name= does not match control_name= or label_width=.
    bool findAttr(const std::string& tag, const std::string& attr,
                  std::string& out)
    {
        const std::string needle = attr + "=\"";
        std::string::size_type pos = 0;
        while ((pos = tag.find(needle, pos)) != std::string::npos)
        {
            const char before = (pos > 0) ? tag[pos - 1] : ' ';
            if (before == ' ' || before == '\t' || before == '\n' ||
                before == '\r')
            {
                std::string::size_type start = pos + needle.size();
                std::string::size_type end = tag.find('"', start);
                if (end == std::string::npos)
                {
                    return false;
                }
                out = tag.substr(start, end - start);
                return true;
            }
            pos += needle.size();
        }
        return false;
    }

    // The relevance model's scope is exactly the 181 CineDiopter* RENDERER
    // inputs.  Floater chrome sits outside it by namespace: CineDiopterUI*
    // (CineDiopterUIActiveOnly -- the section 5.3 display toggle -- and
    // CineDiopterUIRectVersion) is UI state, and the focus-QoL checkboxes
    // bind non-CineDiopter Render* settings (RenderFocusPointCrosshair /
    // RenderFocusPointLocked).  Bindings and resets for those are excluded
    // from the Layer-1 bijection below, exactly as in
    // aldiopterrelevance_oracle.py's _is_modeled_setting().
    bool isModeledSetting(const std::string& setting)
    {
        return setting.compare(0, 11, "CineDiopter") == 0 &&
               setting.compare(0, 13, "CineDiopterUI") != 0;
    }

    struct FloaterScan
    {
        // value-control name -> bound setting (the table's DERIVED column),
        // relevance-model scope only
        std::map<std::string, std::string> mBinding;
        // reset-button name -> commit_callback.parameter, model scope only
        std::map<std::string, std::string> mResets;
    };

    FloaterScan scanFloaterXml()
    {
        const std::string src = readFileOrFail(floaterXmlPath());
        FloaterScan scan;
        std::string::size_type pos = 0;
        while ((pos = src.find('<', pos)) != std::string::npos)
        {
            std::string::size_type end = src.find('>', pos);
            if (end == std::string::npos)
            {
                break;
            }
            const std::string tag = src.substr(pos + 1, end - pos - 1);
            pos = end + 1;

            const std::string::size_type sp = tag.find_first_of(" \t\r\n");
            const std::string elem = tag.substr(0, sp);
            if (elem == "slider" || elem == "combo_box" || elem == "check_box")
            {
                if (elem == "combo_box")
                {
                    // [F8] Spec requirement (design doc section 4.5): every
                    // combo in this floater opts out of wheel-commit --
                    // LLComboBox's wheel handler COMMITS the selection
                    // (llcombobox.cpp:958-997), so a scroll gesture over any
                    // combo would silently mutate render state.
                    std::string name, wheel;
                    findAttr(tag, "name", name);
                    tut::ensure("combo_box '" + name + "' must carry "
                                "wheel_select=\"false\" (design doc 4.5: "
                                "wheel-commit opt-out is mandatory for every "
                                "combo in this floater)",
                                findAttr(tag, "wheel_select", wheel) &&
                                wheel == "false");
                }
                std::string name, setting;
                if (findAttr(tag, "name", name) &&
                    findAttr(tag, "control_name", setting) &&
                    isModeledSetting(setting))
                {
                    tut::ensure("duplicate control " + name,
                                scan.mBinding.count(name) == 0);
                    scan.mBinding[name] = setting;
                }
            }
            else if (elem == "button")
            {
                std::string name, param;
                if (findAttr(tag, "name", name) &&
                    name.compare(0, 4, "rst_") == 0 &&
                    isModeledSetting(name.substr(4)))
                {
                    findAttr(tag, "commit_callback.parameter", param);
                    tut::ensure("duplicate reset " + name,
                                scan.mResets.count(name) == 0);
                    scan.mResets[name] = param;
                }
            }
        }
        return scan;
    }

    // ---------------------------------------------------------------------
    // Invariant W (design doc §4.2, wave 3 / Phase 3): "in every supported
    // configuration ... the vertical scrollbar is not visible." Machine-
    // checked here by walking the ACTUAL XUI -- a future control added to a
    // tab without re-running the generator must fail this test, not
    // silently grow past the viewport. Textual scan only, same house rule
    // as scanFloaterXml() above: never instantiate LLUI.
    // ---------------------------------------------------------------------

    bool isSelfClosingTag(const std::string& tag)
    {
        return !tag.empty() && tag.back() == '/';
    }

    S32 attrInt(const std::string& tag, const std::string& attr, S32 fallback)
    {
        std::string v;
        return findAttr(tag, attr, v) ? atoi(v.c_str()) : fallback;
    }

    // The factory default of UIScrollbarSize, read textually from
    // app_settings/settings.xml -- LLScrollContainer::calcVisibleSize()
    // subtracts exactly this when a scrollbar becomes visible
    // (llscrollcontainer.cpp:445-471: mSize is -1 by default, so the cached
    // control's value is what applies).
    S32 uiScrollbarSizeDefault()
    {
        const std::string src =
            readFileOrFail(testsDir() + "/../app_settings/settings.xml");
        const std::string::size_type key =
            src.find("<key>UIScrollbarSize</key>");
        tut::ensure("UIScrollbarSize present in settings.xml",
                    key != std::string::npos);
        const std::string::size_type val = src.find("<key>Value</key>", key);
        tut::ensure("UIScrollbarSize has a Value",
                    val != std::string::npos);
        // value is serialized as <real>N</real> (typed S32 upstream)
        const std::string::size_type open = src.find('>', src.find('<', val + 16));
        tut::ensure("UIScrollbarSize value tag parses",
                    open != std::string::npos);
        const S32 size = atoi(src.c_str() + open + 1);
        tut::ensure("UIScrollbarSize default is sane", size > 0 && size < 64);
        return size;
    }

    // `pos` must point just past some opening tag's '>'. Depth-counts
    // further "<panel" opens against "</panel>" closes to find the ONE
    // that matches the panel this position is already inside; returns the
    // inner text (that panel's own children, in ITS coordinate frame) and
    // advances `pos` past the matched "</panel>". False if unmatched
    // (malformed/truncated XML -- the caller should fail the test).
    bool consumePanelBody(const std::string& src, std::string::size_type& pos,
                          std::string& out_inner)
    {
        S32 depth = 1;
        std::string::size_type search_from = pos;
        const std::string::size_type body_start = pos;
        while (depth > 0)
        {
            const std::string::size_type next_open = src.find("<panel", search_from);
            const std::string::size_type next_close = src.find("</panel>", search_from);
            if (next_close == std::string::npos)
            {
                return false;
            }
            if (next_open != std::string::npos && next_open < next_close)
            {
                ++depth;
                search_from = next_open + 6;
            }
            else
            {
                --depth;
                if (depth == 0)
                {
                    out_inner = src.substr(body_start, next_close - body_start);
                    pos = next_close + 8; // strlen("</panel>")
                    return true;
                }
                search_from = next_close + 8;
            }
        }
        return false;
    }

    // Finds the "<panel ...>" whose name="panel_name" attribute matches
    // (wherever in the tag that attribute falls -- the tab-body panels this
    // file generates spread their attributes one per line in a different
    // order than the same-rect band panels do, so a fixed "name=\"X\""
    // substring position cannot be assumed) and returns the span between
    // its '>' and the matching "</panel>".
    bool findNamedPanelSpan(const std::string& src, const std::string& panel_name,
                            std::string& out_inner)
    {
        std::string::size_type pos = 0;
        while ((pos = src.find("<panel", pos)) != std::string::npos)
        {
            const std::string::size_type open_end = src.find('>', pos);
            if (open_end == std::string::npos)
            {
                return false;
            }
            const std::string tag = src.substr(pos, open_end - pos + 1);
            std::string name_s;
            if (findAttr(tag, "name", name_s) && name_s == panel_name)
            {
                std::string::size_type body_pos = open_end + 1;
                return consumePanelBody(src, body_pos, out_inner);
            }
            pos = open_end + 1;
        }
        return false;
    }

    // Every element type Invariant W's walk cares about (all of them carry
    // top=/height=). "panel" is handled specially below (it recurses).
    bool isHeightBearingLeaf(const std::string& elem)
    {
        return elem == "slider" || elem == "combo_box" || elem == "check_box" ||
               elem == "button" || elem == "text" || elem == "view_border";
    }

    // Walks `inner` (one panel's children, in that panel's OWN coordinate
    // frame -- every top= here is relative to it) and returns the max
    // bottom edge (top + height) found, recursing into nested <panel>
    // blocks (same-rect overlay bands) by adding the nested panel's own
    // top to everything found inside it -- exactly how LLView resolves a
    // child's screen position from its parent's. Because every same-rect
    // band's sibling panels share an IDENTICAL top/height by construction
    // (enforced by the generator that authored this XML), visiting every
    // one of them (rather than only the one currently visible="true")
    // still yields the correct worst-case max: a duplicate top+height
    // value cannot move the max, and the invisible siblings are exactly
    // the OTHER modes' content this invariant must also cover.
    S32 maxBottomEdge(const std::string& inner)
    {
        S32 max_bottom = 0;
        std::string::size_type pos = 0;
        while ((pos = inner.find('<', pos)) != std::string::npos)
        {
            if (inner.compare(pos, 4, "<!--") == 0)
            {
                const std::string::size_type cend = inner.find("-->", pos);
                if (cend == std::string::npos) { break; }
                pos = cend + 3;
                continue;
            }
            const std::string::size_type tag_end = inner.find('>', pos);
            if (tag_end == std::string::npos) { break; }
            const std::string tag = inner.substr(pos + 1, tag_end - pos - 1);
            const std::string::size_type after_tag = tag_end + 1;

            if (!tag.empty() && tag[0] == '/')
            {
                pos = after_tag;
                continue;
            }
            const std::string::size_type sp = tag.find_first_of(" \t\r\n");
            const std::string elem = tag.substr(0, sp == std::string::npos ? tag.size() : sp);

            std::string top_s, h_s;
            const bool has_geom = findAttr(tag, "top", top_s) && findAttr(tag, "height", h_s);

            if (elem == "panel" && !isSelfClosingTag(tag))
            {
                std::string body;
                std::string::size_type body_pos = after_tag;
                if (consumePanelBody(inner, body_pos, body))
                {
                    const S32 nested_max = maxBottomEdge(body);
                    if (has_geom)
                    {
                        const S32 top = atoi(top_s.c_str());
                        const S32 h = atoi(h_s.c_str());
                        max_bottom = llmax(max_bottom, top + llmax(h, nested_max));
                    }
                    pos = body_pos;
                    continue;
                }
            }

            if (has_geom && isHeightBearingLeaf(elem))
            {
                const S32 top = atoi(top_s.c_str());
                const S32 h = atoi(h_s.c_str());
                max_bottom = llmax(max_bottom, top + h);
            }
            pos = after_tag;
        }
        return max_bottom;
    }

    // Finds the raw text of the first tag literally "<tag_name" (word-
    // boundary checked so "panel" cannot match "panelfoo"), for reading a
    // handful of top-level attributes off it.
    bool findOpenTagText(const std::string& src, const std::string& tag_name,
                         std::string& out_tag_text)
    {
        const std::string needle = "<" + tag_name;
        std::string::size_type start = 0;
        while ((start = src.find(needle, start)) != std::string::npos)
        {
            const char after = (start + needle.size() < src.size())
                ? src[start + needle.size()] : ' ';
            if (after == ' ' || after == '\t' || after == '\n' || after == '\r' ||
                after == '/' || after == '>')
            {
                const std::string::size_type end = src.find('>', start);
                if (end == std::string::npos) { return false; }
                out_tag_text = src.substr(start, end - start + 1);
                return true;
            }
            start += needle.size();
        }
        return false;
    }

    // Finds the first "<tag_name ...>" whose name="..." attribute equals
    // name_value (scroll_container/panel tags repeat across the 9 tabs, so
    // findOpenTagText's "first occurrence" is not enough for these).
    bool findTagByNameAttr(const std::string& src, const std::string& tag_name,
                          const std::string& name_value, std::string& out_tag_text)
    {
        std::string::size_type pos = 0;
        const std::string needle = "<" + tag_name;
        while ((pos = src.find(needle, pos)) != std::string::npos)
        {
            const std::string::size_type end = src.find('>', pos);
            if (end == std::string::npos) { return false; }
            const std::string tag = src.substr(pos, end - pos + 1);
            std::string name_s;
            if (findAttr(tag, "name", name_s) && name_s == name_value)
            {
                out_tag_text = tag;
                return true;
            }
            pos = end + 1;
        }
        return false;
    }

    struct TabSpec { const char* mLabel; const char* mInnerPanel; const char* mScrollContainer; };
    const TabSpec DIOPTER_TABS[] =
    {
        { "Main",          "diopter_inner_main",    "diopter_scroll_main" },
        { "Shape",         "diopter_inner_shape",   "diopter_scroll_shape" },
        { "Focus",         "diopter_inner_focus",   "diopter_scroll_focus" },
        { "Glass",         "diopter_inner_glass",   "diopter_scroll_glass" },
        { "Halo & Ghosts", "diopter_inner_halo",    "diopter_scroll_halo" },
        { "Bokeh",         "diopter_inner_bokeh",   "diopter_scroll_bokeh" },
        { "Motion",        "diopter_inner_motion",  "diopter_scroll_motion" },
        { "Kaleido",       "diopter_inner_kaleido", "diopter_scroll_kaleido" },
        { "Kal Anim",      "diopter_inner_kalanim", "diopter_scroll_kalanim" },
    };
    constexpr S32 AL_DIOPTER_TAB_COUNT = 9;

    // ---------------------------------------------------------------------
    // The preset-owned lists, hardcoded per the design doc's Layer-1 spec.
    // Canonical source: aldiopterpresetbank.cpp diopterOwnedNames() /
    // kaleidoOwnedNames() (44 + 49; the auto-Custom listener install in
    // llviewerfloaterreg.cpp reads those same lists).  If either list
    // changes there, this copy must change with it -- that is the point:
    // the diff is the review artifact.
    // ---------------------------------------------------------------------

    const char* const DIOPTER_OWNED[44] =
    {
        "CineDiopterShape", "CineDiopterContent", "CineDiopterHollow",
        "CineDiopterArcLengthDeg", "CineDiopterBrokenCount", "CineDiopterCharacter",
        "CineDiopterGlassProfile", "CineDiopterIOR", "CineDiopterThickness",
        "CineDiopterRimWidth", "CineDiopterRimWarp", "CineDiopterRimCaustic",
        "CineDiopterRimDarken", "CineDiopterApertureShape", "CineDiopterBlades",
        "CineDiopterBladeCurve", "CineDiopterAnamorph", "CineDiopterCatEye",
        "CineDiopterSpotBlur", "CineDiopterBokehHighlight", "CineDiopterRingCount",
        "CineDiopterRingFold", "CineDiopterRingPhase", "CineDiopterTwistDeg",
        "CineDiopterLobeAmt", "CineDiopterLobeCount", "CineDiopterLobePhaseDeg",
        "CineDiopterGhostCount", "CineDiopterGhostSpacing", "CineDiopterTangentSmear",
        "CineDiopterRadialSmear", "CineDiopterGhostGain", "CineDiopterDispersion",
        "CineDiopterPatternMode", "CineDiopterPatternSegments", "CineDiopterPatternFeedDeg",
        "CineDiopterPatternZoom", "CineDiopterMotionMode", "CineDiopterHandheld",
        "CineDiopterHandheldSpeed", "CineDiopterSpinMode", "CineDiopterSpinSpeed",
        "CineDiopterSeamGhostPx", "CineDiopterPlacementMode",
    };

    const char* const KALEIDO_OWNED[49] =
    {
        "CineDiopterKalMode", "CineDiopterKalEdgeWrap", "CineDiopterKalProtectMode",
        "CineDiopterKalProtectAnchor", "CineDiopterKalMotionMode", "CineDiopterKalPulseTarget",
        "CineDiopterKalSpinMode", "CineDiopterKalSegments", "CineDiopterKalAngle",
        "CineDiopterKalTwist", "CineDiopterKalRingCount", "CineDiopterKalStarSharp",
        "CineDiopterKalShapeBias", "CineDiopterKalSourceAngle", "CineDiopterKalSourceZoom",
        "CineDiopterKalSourceOffsetX", "CineDiopterKalSourceOffsetY", "CineDiopterKalSourceSpin",
        "CineDiopterKalFXBand", "CineDiopterKalFXAmount", "CineDiopterKalFXFlow",
        "CineDiopterKalFXFreq", "CineDiopterKalProtectRadius", "CineDiopterKalProtectFeather",
        "CineDiopterKalDepthCut", "CineDiopterKalDepthFeatherM", "CineDiopterKalDepthInvert",
        "CineDiopterKalPingPong", "CineDiopterKalSpeed", "CineDiopterKalMotionAngle",
        "CineDiopterKalSweepRange", "CineDiopterKalPulseAmt", "CineDiopterKalWaveAmp",
        "CineDiopterKalWaveFreq", "CineDiopterKalPathFreqX", "CineDiopterKalPathFreqY",
        "CineDiopterKalPathPhase", "CineDiopterKalPathAmp", "CineDiopterKalSpinSpeed",
        "CineDiopterKalSpinTravel", "CineDiopterKalSpinDuration", "CineDiopterKalSpinBounce",
        "CineDiopterKalSpinDelay", "CineDiopterKalSeamSoften", "CineDiopterKalCellSizeVar",
        "CineDiopterKalCellBreathe", "CineDiopterKalCellSubdiv", "CineDiopterKalCellMerge",
        "CineDiopterKalCellTint",
    };

    // ---------------------------------------------------------------------
    // Oracle model -- the committed per-branch consumed sets
    // (aldiopterrelevance_oracle.llsd), loaded once into typed containers.
    // ---------------------------------------------------------------------

    typedef std::set<std::string> StrSet;

    StrSet setOf(const LLSD& array)
    {
        StrSet out;
        for (LLSD::array_const_iterator it = array.beginArray();
             it != array.endArray(); ++it)
        {
            out.insert(it->asString());
        }
        return out;
    }

    std::vector<StrSet> vecOf(const LLSD& array, size_t expected)
    {
        std::vector<StrSet> out;
        for (LLSD::array_const_iterator it = array.beginArray();
             it != array.endArray(); ++it)
        {
            out.push_back(setOf(*it));
        }
        tut::ensure_equals("oracle branch-array size", out.size(), expected);
        return out;
    }

    std::set<S32> intsOf(const LLSD& array)
    {
        std::set<S32> out;
        for (LLSD::array_const_iterator it = array.beginArray();
             it != array.endArray(); ++it)
        {
            out.insert((S32)it->asInteger());
        }
        return out;
    }

    struct OracleModel
    {
        StrSet mMasterEnable;
        StrSet mToolShared;

        // diopter
        StrSet dAlways, dFreeze, dFramedHeader, dOnLens, dSize, dHollow,
               dWobbleFreq, dRefraction, dWarpParams, dGhosts, dFaceted,
               dSeam, dAberration, dAxial, dCharacter, dPower, dLensM,
               dBaseM, dFloorMax, dSpotBlur, dMagScale, dMagTrim, dPulseAmt,
               dWaveAmp, dStutterFocus, dHandheld, dHandheldFocus;
        std::vector<StrSet> dMaskShape, dMotion, dSpin, dAperture;

        // kaleido
        StrSet kAlways, kFreeze, kFxFlow, kWave, kPulseOffsetExtra,
               kAnchorFixed;
        std::vector<StrSet> kMode, kMotion, kSpin, kProtect;
        std::set<S32> kFlowCellModes, kWaveModes;
    };

    const OracleModel& oracleModel()
    {
        static OracleModel model;
        static bool loaded = false;
        if (!loaded)
        {
            std::ifstream in(oracleLlsdPath().c_str(),
                             std::ios::in | std::ios::binary);
            tut::ensure("oracle llsd readable", in.good());
            LLSD sd;
            LLSDSerialize::fromXML(sd, in);
            tut::ensure("oracle llsd is a map", sd.isMap());
            tut::ensure_equals("oracle version", sd["version"].asInteger(), 1);

            model.mMasterEnable = setOf(sd["master_enable"]);
            model.mToolShared = setOf(sd["tool_shared_always"]);

            const LLSD& d = sd["diopter"];
            model.dAlways = setOf(d["always"]);
            model.dFreeze = setOf(d["freeze_dependent"]);
            model.dFramedHeader = setOf(d["framed_header"]);
            model.dMaskShape = vecOf(d["mask_shape"], 12);
            model.dOnLens = setOf(d["onlens_mask"]);
            model.dSize = setOf(d["size"]);
            model.dHollow = setOf(d["hollow"]);
            model.dWobbleFreq = setOf(d["wobble_freq"]);
            model.dRefraction = setOf(d["refraction"]);
            model.dWarpParams = setOf(d["warp_params"]);
            model.dGhosts = setOf(d["ghosts"]);
            model.dFaceted = setOf(d["faceted"]);
            model.dSeam = setOf(d["seam"]);
            model.dAberration = setOf(d["aberration"]);
            model.dAxial = setOf(d["aberration_axial"]);
            model.dCharacter = setOf(d["character"]);
            model.dPower = setOf(d["power"]);
            model.dLensM = setOf(d["lens_m"]);
            model.dBaseM = setOf(d["base_m"]);
            model.dFloorMax = setOf(d["floor_max"]);
            model.dSpotBlur = setOf(d["spot_blur"]);
            model.dMagScale = setOf(d["mag_scale"]);
            model.dMagTrim = setOf(d["mag_trim"]);
            model.dMotion = vecOf(d["motion"], 12);
            model.dPulseAmt = setOf(d["pulse_amt"]);
            model.dWaveAmp = setOf(d["wave_amp"]);
            model.dStutterFocus = setOf(d["stutter_focus"]);
            model.dHandheld = setOf(d["handheld"]);
            model.dHandheldFocus = setOf(d["handheld_focus"]);
            model.dSpin = vecOf(d["spin"], 4);
            model.dAperture = vecOf(d["aperture"], 5);

            const LLSD& k = sd["kaleido"];
            model.kAlways = setOf(k["always"]);
            model.kFreeze = setOf(k["freeze_dependent"]);
            model.kMode = vecOf(k["mode"], 24);
            model.kFlowCellModes = intsOf(k["flow_cell_modes"]);
            model.kFxFlow = setOf(k["fx_flow"]);
            model.kWaveModes = intsOf(k["wave_modes"]);
            model.kWave = setOf(k["wave"]);
            model.kMotion = vecOf(k["motion"], 12);
            model.kPulseOffsetExtra = setOf(k["pulse_offset_extra"]);
            model.kSpin = vecOf(k["spin"], 4);
            model.kProtect = vecOf(k["protect"], 4);
            model.kAnchorFixed = setOf(k["anchor_fixed"]);
            loaded = true;
        }
        return model;
    }

    void addAll(StrSet& out, const StrSet& in)
    {
        out.insert(in.begin(), in.end());
    }

    // ---------------------------------------------------------------------
    // alOracleConsumedSet -- recombine the oracle's per-branch sets with the
    // renderer's gate structure.  Each gate cites the renderer location it
    // mirrors; the per-branch membership itself lives in the .llsd.  This is
    // a second, independent factorization of relevance (branch-union form vs
    // the table's per-control OR-of-AND form) -- the comparison of the two
    // over the sweep corpus is Layer 2's correctness assertion.
    // ---------------------------------------------------------------------

    std::set<std::string> alOracleConsumedSet(const ALDiopterState& st)
    {
        const OracleModel& m = oracleModel();
        StrSet out = m.mMasterEnable;   // Tier 0: relevant even when disabled
        if (!st.mEnabled)
        {
            // pipeline.cpp master-enable gate: everything else is inert
            return out;
        }
        addAll(out, m.mToolShared);     // Tool Mode row (AL_TOOL_BOTH)

        if (st.mToolMode == 0)          // ---- Ultimate Diopter ----
        {
            addAll(out, m.dAlways);
            if (st.mFreeze)
            {
                addAll(out, m.dFreeze);             // Freeze At
            }
            const bool warp = alDiopterEvalPred(PRED_WARP_ARMED, st);
            if (st.mPlacementMode == 0)             // framed
            {
                addAll(out, m.dFramedHeader);       // Shape / Contents combos
                addAll(out, m.dMaskShape[st.mShape]);
                // Size: mask boundary (shapes 2-11) OR refraction radius OR
                // warp annulus outer -- all three discarded under On-Lens
                // (pipeline.cpp:14289-14296; table row 8)
                if (st.mShape >= 2 || st.mGlassProfile > 0 || warp)
                {
                    addAll(out, m.dSize);
                }
                // Hollow as mask onion, shapes 3-11 (table row 20 C1)
                if (st.mShape >= 3)
                {
                    addAll(out, m.dHollow);
                }
            }
            else                                    // On-Lens
            {
                addAll(out, m.dOnLens);
            }
            if (warp)
            {
                // warp dependents + Hollow's annulus-inner path, which is
                // placement-independent (glsl:399; table row 20 C2)
                addAll(out, m.dWarpParams);
                addAll(out, m.dHollow);
            }
            // Wobble Frequency: shared spatial density -- static Edge Wobble
            // OR Motion = Wave, both needing an edge (Codex C2; row 25)
            if (alDiopterEvalPred(PRED_SHAPE_HAS_EDGE, st) &&
                (alDiopterEvalPred(PRED_EDGE_WOBBLE_ARMED, st) ||
                 st.mMotionMode == 3))
            {
                addAll(out, m.dWobbleFreq);
            }
            if (st.mGlassProfile > 0)               // glsl:336
            {
                addAll(out, m.dRefraction);
            }
            if (alDiopterEvalPred(PRED_GHOSTS_ARMED, st))   // glsl:107
            {
                addAll(out, m.dGhosts);
            }
            if (st.mPatternMode >= 1 && st.mPatternMode <= 3)
            {
                addAll(out, m.dFaceted);
            }
            if (alDiopterEvalPred(PRED_SEAM_ARMED, st))     // glsl:90
            {
                addAll(out, m.dSeam);
            }
            const bool powered = alDiopterEvalPred(PRED_LENS_POWERED, st);
            if (powered)                            // pipeline:14249
            {
                addAll(out, m.dCharacter);
            }
            if (alDiopterEvalPred(PRED_ABERRATION_ARMED, st))
            {
                addAll(out, m.dAberration);         // pipeline:14253-14256
                if (st.mContent == 0)
                {
                    addAll(out, m.dAxial);          // zeroed at :14265
                }
            }
            // exactly one of Power / Lens Distance is always dead
            addAll(out, (st.mLensFocusMode == 0) ? m.dPower : m.dLensM);
            if (st.mBaseFocusProvenance == AL_DIOPTER_FOCUS_MANUAL)
            {
                addAll(out, m.dBaseM);              // pipeline:14203-14232
            }
            if (alDiopterEvalPred(PRED_FIELD_CURVE_ARMED, st) ||
                st.mContent == 1)
            {
                addAll(out, m.dFloorMax);           // glsl:592-595 OR rule
            }
            if (st.mContent == 1)
            {
                addAll(out, m.dSpotBlur);           // Sharp Window only
            }
            if (st.mGlassProfile == 0 && st.mContent == 0)
            {
                addAll(out, m.dMagTrim);            // magnify = 1.f otherwise
                if (powered)
                {
                    addAll(out, m.dMagScale);       // multiplicative (row 93)
                }
            }
            addAll(out, m.dMotion[st.mMotionMode]);
            // Pulse Amount: Pulse with Size target, Pulse with Focus target
            // outside Sharp Window (the rack is discarded at :14261-14266),
            // or Heartbeat (row 101)
            if ((st.mMotionMode == 2 &&
                 (st.mPulseTarget == 0 ||
                  (st.mPulseTarget == 1 && st.mContent == 0))) ||
                st.mMotionMode == 10)
            {
                addAll(out, m.dPulseAmt);
            }
            // Wave needs an edge to undulate (Codex C1; row 102)
            if (st.mMotionMode == 3 &&
                alDiopterEvalPred(PRED_SHAPE_HAS_EDGE, st))
            {
                addAll(out, m.dWaveAmp);
            }
            // Stutter Focus is double-guarded (pipeline:14092; row 111)
            if (st.mMotionMode == 5 && st.mContent == 0)
            {
                addAll(out, m.dStutterFocus);
            }
            if (alDiopterEvalPred(PRED_HANDHELD_ARMED, st))
            {
                addAll(out, m.dHandheld);           // pipeline:14154
                if (st.mContent == 0)
                {
                    addAll(out, m.dHandheldFocus);  // pipeline:14165
                }
            }
            addAll(out, m.dSpin[st.mSpinMode]);
            addAll(out, m.dAperture[st.mApertureShape]);
        }
        else                            // ---- Ultimate Kaleidoscope ----
        {
            addAll(out, m.kAlways);
            if (st.mKalFreeze)
            {
                addAll(out, m.kFreeze);
            }
            addAll(out, m.kMode[st.mKalMode]);
            // FX Flow's Tier-C path: cell modes reach ft only through
            // kal_cellScale, a no-op unless Cell Breathe > 0
            // (glsl:110-118; Codex 1.8; row 142 C2)
            if (m.kFlowCellModes.count((S32)st.mKalMode) &&
                alDiopterEvalPred(PRED_CELL_BREATHE_ARMED, st))
            {
                addAll(out, m.kFxFlow);
            }
            addAll(out, m.kMotion[st.mKalMotionMode]);
            // Pulse target Offset also consumes the direction angle
            // (pipeline alKaleidoResolveMotion case 2 else-branch; row 154 C2)
            if (st.mKalMotionMode == 2 && st.mKalPulseTarget == 2)
            {
                addAll(out, m.kPulseOffsetExtra);
            }
            // Wave rows need Motion = Wave AND a wave-evaluating pattern
            // (design doc 2.2 Wv column; rows 159/160)
            if (st.mKalMotionMode == 3 && m.kWaveModes.count((S32)st.mKalMode))
            {
                addAll(out, m.kWave);
            }
            addAll(out, m.kSpin[st.mKalSpinMode]);
            addAll(out, m.kProtect[st.mKalProtectMode]);
            // Protect Center X/Y: disc protect present AND Anchor = Fixed
            // (pipeline:14997-15008; rows 175/176)
            if ((st.mKalProtectMode == 1 || st.mKalProtectMode == 3) &&
                st.mKalProtectAnchor == 1)
            {
                addAll(out, m.kAnchorFixed);
            }
        }
        return out;
    }

    // ---------------------------------------------------------------------
    // The sweep corpus, S0-S8 exactly as design doc 2.3 tabulates.
    // Cardinalities: 4 + 240 + 96 + 576 + 576 + 20 + 12 + 40 + 16 = 1580.
    //
    // Non-axis drivers sit at the settings.xml factory defaults
    // (ALDiopterState's member initializers).  Drivers that no tabulated
    // axis varies -- Freeze, diopter Spin, and the kaleido Spin / Protect /
    // Anchor / PulseTarget / Freeze -- are piggybacked deterministically
    // onto existing axes (documented per sweep below) so the clause-coverage
    // meta-rule can observe their clauses both passing and failing without
    // changing any sweep's advertised cardinality.
    // ---------------------------------------------------------------------

    struct ALSweep
    {
        const char* mName;
        std::vector<ALDiopterState> mStates;
        std::vector<ALDiopterState>::const_iterator begin() const
        {
            return mStates.begin();
        }
        std::vector<ALDiopterState>::const_iterator end() const
        {
            return mStates.end();
        }
    };

    std::vector<ALSweep> buildSweeps()
    {
        std::vector<ALSweep> sweeps;

        // S0 -- enabled x tool-mode: the master-enable Tier-0 gate, and the
        // FALSE state of every ALWAYS clause (the only sweep with Enabled
        // off; without it ALWAYS clauses could never be observed failing).
        {
            ALSweep s; s.mName = "S0";
            for (U32 e = 0; e <= 1; ++e)
            {
                for (U32 t = 0; t <= 1; ++t)
                {
                    ALDiopterState st;
                    st.mEnabled = (e != 0);
                    st.mToolMode = t;
                    s.mStates.push_back(st);
                }
            }
            sweeps.push_back(s);
        }

        // S1 -- shape x placement x profile x warp-armed (12*2*5*2 = 240):
        // the Size / Hollow OR-consumption and D1's On-Lens discard.
        {
            ALSweep s; s.mName = "S1";
            for (U32 sh = 0; sh < 12; ++sh)
                for (U32 pl = 0; pl <= 1; ++pl)
                    for (U32 pr = 0; pr < 5; ++pr)
                        for (U32 w = 0; w <= 1; ++w)
                        {
                            ALDiopterState st;
                            st.mEnabled = true;
                            st.mShape = sh;
                            st.mPlacementMode = pl;
                            st.mGlassProfile = pr;
                            st.mRingFold = w ? 0.5f : 0.f;  // arming input
                            s.mStates.push_back(st);
                        }
            sweeps.push_back(s);
        }

        // S2 -- motion x pulse-target x content x handheld-armed
        // (12*2*2*2 = 96): the Sharp Window guards on Stutter Focus, Focus
        // Breath, Pulse:Focus.  Piggyback: SpinMode = motion % 4 flips the
        // Spin=Constant / Spin{1,2,3} / Spin{3} clauses both ways.
        {
            ALSweep s; s.mName = "S2";
            for (U32 mo = 0; mo < 12; ++mo)
                for (U32 pt = 0; pt <= 1; ++pt)
                    for (U32 c = 0; c <= 1; ++c)
                        for (U32 h = 0; h <= 1; ++h)
                        {
                            ALDiopterState st;
                            st.mEnabled = true;
                            st.mMotionMode = mo;
                            st.mPulseTarget = pt;
                            st.mContent = c;
                            st.mHandheld = h ? 0.6f : 0.f;
                            st.mSpinMode = mo % 4;
                            s.mStates.push_back(st);
                        }
            sweeps.push_back(s);
        }

        // S3 -- shape x placement x motion x edge-wobble-armed
        // (12*2*12*2 = 576): C1 (Wave inert under Full Frame / On-Lens) and
        // C2 (WobbleFreq's OR rule).
        {
            ALSweep s; s.mName = "S3";
            for (U32 sh = 0; sh < 12; ++sh)
                for (U32 pl = 0; pl <= 1; ++pl)
                    for (U32 mo = 0; mo < 12; ++mo)
                        for (U32 w = 0; w <= 1; ++w)
                        {
                            ALDiopterState st;
                            st.mEnabled = true;
                            st.mShape = sh;
                            st.mPlacementMode = pl;
                            st.mMotionMode = mo;
                            st.mWobbleAmt = w ? 0.15f : 0.f;
                            s.mStates.push_back(st);
                        }
            sweeps.push_back(s);
        }

        // S4 -- kal-mode x cell-breathe x kal-motion (24*2*12 = 576): D2's
        // mask and the Tier-C FX Flow path.  Piggybacks: KalSpin = mode % 4,
        // KalPulseTarget = mode % 3, KalProtect = motion % 4, KalAnchor and
        // KalFreeze ride the breathe axis -- together they flip every
        // kaleido Spin / Protect / Anchor / PulseTarget / Freeze clause.
        {
            ALSweep s; s.mName = "S4";
            for (U32 k = 0; k < 24; ++k)
                for (U32 b = 0; b <= 1; ++b)
                    for (U32 mo = 0; mo < 12; ++mo)
                    {
                        ALDiopterState st;
                        st.mEnabled = true;
                        st.mToolMode = 1;
                        st.mKalMode = k;
                        st.mCellBreathe = b ? 0.4f : 0.f;
                        st.mKalMotionMode = mo;
                        st.mKalSpinMode = k % 4;
                        st.mKalPulseTarget = k % 3;
                        st.mKalProtectMode = mo % 4;
                        st.mKalProtectAnchor = b ? 1 : 0;
                        st.mKalFreeze = (b != 0);
                        s.mStates.push_back(st);
                    }
            sweeps.push_back(s);
        }

        // S5 -- aperture-shape x pattern-mode (5*4 = 20): Rotation
        // membership {1,2,3}, and WARP_ARMED via the pattern arm.
        {
            ALSweep s; s.mName = "S5";
            for (U32 a = 0; a < 5; ++a)
                for (U32 p = 0; p < 4; ++p)
                {
                    ALDiopterState st;
                    st.mEnabled = true;
                    st.mApertureShape = a;
                    st.mPatternMode = p;
                    s.mStates.push_back(st);
                }
            sweeps.push_back(s);
        }

        // S6 -- focus-mode x lens-mode x provenance (2*2*3 = 12): the
        // three-way Base Distance ambiguity.  Manual focus mode coerces
        // provenance to MANUAL (the resolver never overrides the slider
        // there, pipeline:14204/14213 both require focus_mode == 1).
        // Piggyback: Freeze rides the lens-mode axis for row 13.
        {
            ALSweep s; s.mName = "S6";
            for (U32 fm = 0; fm <= 1; ++fm)
                for (U32 lm = 0; lm <= 1; ++lm)
                    for (U32 pv = 0; pv < 3; ++pv)
                    {
                        ALDiopterState st;
                        st.mEnabled = true;
                        st.mFocusMode = fm;
                        st.mLensFocusMode = lm;
                        st.mBaseFocusProvenance =
                            (fm == 0) ? AL_DIOPTER_FOCUS_MANUAL
                                      : (ALDiopterFocusProvenance)pv;
                        st.mResolvedBaseFocusM =
                            (st.mBaseFocusProvenance ==
                             AL_DIOPTER_FOCUS_MANUAL) ? 8.f : 12.4f;
                        st.mFreeze = (lm == 1);
                        s.mStates.push_back(st);
                    }
            sweeps.push_back(s);
        }

        // S7 -- ghosts-armed x seam-armed x content x profile
        // (2*2*2*5 = 40): the 7 ghost dependents, Seam Double Amount, and
        // Magnify's profile-OR-content rule.
        {
            ALSweep s; s.mName = "S7";
            for (U32 g = 0; g <= 1; ++g)
                for (U32 sm = 0; sm <= 1; ++sm)
                    for (U32 c = 0; c <= 1; ++c)
                        for (U32 pr = 0; pr < 5; ++pr)
                        {
                            ALDiopterState st;
                            st.mEnabled = true;
                            st.mGhostCount = g ? 3.f : 0.f;
                            st.mSeamPx = sm ? 6.f : 0.f;
                            st.mContent = c;
                            st.mGlassProfile = pr;
                            s.mStates.push_back(st);
                        }
            sweeps.push_back(s);
        }

        // S8 -- character x plane-separation x field-scale x content
        // (2*2*2*2 = 16): the four aberration controls, Surround Max Blur's
        // OR rule, and Magnify Scale's multiplicative gate.  Plane
        // separation is driven by the UNDERLYING distance settings (manual
        // lens mode, Lens Distance equal to / different from Base Distance),
        // never by writing the derived strength_d.
        {
            ALSweep s; s.mName = "S8";
            for (U32 ch = 0; ch <= 1; ++ch)
                for (U32 sep = 0; sep <= 1; ++sep)
                    for (U32 fs = 0; fs <= 1; ++fs)
                        for (U32 c = 0; c <= 1; ++c)
                        {
                            ALDiopterState st;
                            st.mEnabled = true;
                            st.mCharacter = ch ? 1.f : 0.f;
                            st.mLensFocusMode = 1;      // manual lens plane
                            st.mFocusMode = 0;          // manual base plane
                            st.mBaseFocusProvenance = AL_DIOPTER_FOCUS_MANUAL;
                            st.mBaseFocusM = 8.f;
                            st.mResolvedBaseFocusM = 8.f;
                            st.mLensFocusM = sep ? 4.f : 8.f;
                            st.mFieldScale = fs ? 1.f : 0.f;
                            st.mContent = c;
                            s.mStates.push_back(st);
                        }
            sweeps.push_back(s);
        }

        return sweeps;
    }

    const std::vector<ALSweep>& sSweepsRef()
    {
        static const std::vector<ALSweep> sweeps = buildSweeps();
        return sweeps;
    }

    // ---------------------------------------------------------------------
    // Coverage bitmaps and assertions -- verbatim from design doc 2.3.
    // ---------------------------------------------------------------------

    struct ALCoverage
    {
        // [pred][state] -- state 0 = observed false, 1 = observed true.
        // PRED_NONE occupies slot 0 and is never written or checked.
        bool mPred[AL_PRED_COUNT][2] = {};
        // [row][clause][state]; AL_MAX_CLAUSES == 3 per the schema.
        bool mClause[AL_RELEVANCE_COUNT][AL_MAX_CLAUSES][2] = {};
        // [row][state] -- the row's overall relevance verdict.
        bool mRow[AL_RELEVANCE_COUNT][2] = {};
    };

    // Called once per sweep case, after evaluating the table against `st`.
    void alAccumulateCoverage(const ALDiopterState& st, ALCoverage& cov)
    {
        for (S32 p = PRED_NONE + 1; p < AL_PRED_COUNT; ++p)
        {
            cov.mPred[p][alDiopterEvalPred((ALDiopterPred)p, st) ? 1 : 0] = true;
        }

        for (S32 r = 0; r < AL_RELEVANCE_COUNT; ++r)
        {
            const ALDiopterRelevance& row = sRelevance[r];
            // mClauseCount, not a sentinel scan: ALWAYS clauses (mTermCount
            // == 0) are real clauses and are accumulated here like any other.
            for (S32 c = 0; c < row.mClauseCount; ++c)
            {
                const bool pass = alDiopterEvalClause(row, c, st);
                cov.mClause[r][c][pass ? 1 : 0] = true;
            }
            cov.mRow[r][alDiopterEvaluate(row, st) ? 1 : 0] = true;
        }
    }

    void alAssertCoverage(const ALCoverage& cov)
    {
        for (S32 p = PRED_NONE + 1; p < AL_PRED_COUNT; ++p)
        {
            for (S32 s = 0; s < 2; ++s)
            {
                tut::ensure(llformat(
                    "predicate %s never observed %s across the sweep corpus -- "
                    "add a sweep axis that varies it (design doc SS2.3)",
                    alDiopterPredName((ALDiopterPred)p), s ? "true" : "false"),
                    cov.mPred[p][s]);
            }
        }

        for (S32 r = 0; r < AL_RELEVANCE_COUNT; ++r)
        {
            const ALDiopterRelevance& row = sRelevance[r];
            if (row.mUnconditional)
            {
                // diopter_enabled: never irrelevant by design. Assert that
                // the exemption is not being used to hide an untested row.
                tut::ensure("only diopter_enabled may be UNCONDITIONAL",
                            std::string(row.mCtrlName) == "diopter_enabled");
                continue;
            }

            for (S32 s = 0; s < 2; ++s)
            {
                tut::ensure(llformat("row %s never observed %s -- unreachable "
                                     "or always-on rule", row.mCtrlName,
                                     s ? "relevant" : "irrelevant"),
                            cov.mRow[r][s]);
            }

            for (S32 c = 0; c < row.mClauseCount; ++c)
            {
                tut::ensure(llformat("row %s clause %d never PASSES -- "
                                     "unreachable clause", row.mCtrlName, c),
                            cov.mClause[r][c][1]);
                tut::ensure(llformat("row %s clause %d never FAILS -- dead "
                                     "clause, the terms are implied by "
                                     "something else", row.mCtrlName, c),
                            cov.mClause[r][c][0]);
            }
        }
    }

    // The per-case correctness assertion, with set-difference diagnostics
    // (a raw ensure_equals on two std::sets cannot name the offenders).
    void alEnsureSameSet(const std::string& label,
                         const std::set<std::string>& table_set,
                         const std::set<std::string>& oracle_set)
    {
        if (table_set == oracle_set)
        {
            return;
        }
        std::string msg = label + " relevant-set != oracle consumed-set;";
        for (const std::string& name : table_set)
        {
            if (oracle_set.count(name) == 0)
            {
                msg += " table-only:" + name;
            }
        }
        for (const std::string& name : oracle_set)
        {
            if (table_set.count(name) == 0)
            {
                msg += " oracle-only:" + name;
            }
        }
        tut::ensure(msg, false);
    }

    void alRunSweeps(ALCoverage& cov)
    {
        S32 cases = 0;
        for (const ALSweep& sweep : sSweepsRef())          // S0..S8
        {
            for (const ALDiopterState& st : sweep)  // iterates the cross product
            {
                // 1. the correctness assertion: table vs oracle
                alEnsureSameSet(llformat("%s case %d", sweep.mName, cases),
                                alDiopterRelevantSet(st),
                                alOracleConsumedSet(st));
                // 2. the adequacy accumulation
                alAccumulateCoverage(st, cov);
                ++cases;
            }
        }
        tut::ensure_equals("sweep corpus size changed unexpectedly",
                           cases, 1580);
    }
}

namespace tut
{
    struct aldiopterrelevance_data {};
    typedef test_group<aldiopterrelevance_data> aldiopterrelevance_group;
    typedef aldiopterrelevance_group::object aldiopterrelevance_object;
    aldiopterrelevance_group aldiopterrelevance_tests("ALDiopterRelevance");

    // The Layer-2 entry point -- the accumulate/assert pair is actually
    // WIRED, not implied [Codex delta-5 finding 1]: sweeps run (each case
    // asserting table == oracle), then adequacy is asserted.
    template<> template<>
    void aldiopterrelevance_object::test<1>()
    {
        ALCoverage cov;
        alRunSweeps(cov);        // correctness (table vs oracle) + accumulation
        alAssertCoverage(cov);   // adequacy (predicate-flip + clause coverage)
    }

    // Layer 1 -- structural validation against the XUI and the owned lists.
    template<> template<>
    void aldiopterrelevance_object::test<2>()
    {
        const FloaterScan scan = scanFloaterXml();
        ensure_equals("181 relevance-model controls in the floater XML "
                      "(UI-chrome bindings excluded by namespace)",
                      (S32)scan.mBinding.size(), 181);
        ensure_equals("180 model-scope reset buttons in the floater XML",
                      (S32)scan.mResets.size(), 180);

        std::set<std::string> owned;
        for (const char* name : DIOPTER_OWNED) { owned.insert(name); }
        for (const char* name : KALEIDO_OWNED) { owned.insert(name); }
        ensure_equals("44 + 49 distinct owned settings",
                      (S32)owned.size(), 93);

        const ALDiopterState defaults;   // factory defaults; any state works
                                         // for term-name resolution
        std::set<std::string> seen_settings;
        S32 null_resets = 0;
        S32 unconditional = 0;
        S32 owned_rows = 0;
        S32 total_clauses = 0;

        for (S32 r = 0; r < AL_RELEVANCE_COUNT; ++r)
        {
            const ALDiopterRelevance& row = sRelevance[r];
            // an under-filled aggregate would zero-fill silently; catch it
            // before constructing strings from nullptr
            ensure(llformat("row %d has a control name", r),
                   row.mCtrlName != nullptr);
            const std::string ctrl = row.mCtrlName;

            // control resolves, and its DERIVED setting is unique
            const std::map<std::string, std::string>::const_iterator bound =
                scan.mBinding.find(ctrl);
            ensure("control resolves in XML: " + ctrl,
                   bound != scan.mBinding.end());
            const std::string setting = bound->second;
            ensure("setting seen once: " + setting,
                   seen_settings.insert(setting).second);

            // reset resolution; nullable for exactly one row [Codex A10]
            if (!row.mResetName)
            {
                ++null_resets;
                ensure("null reset only on diopter_enabled",
                       ctrl == "diopter_enabled");
            }
            else
            {
                const std::string reset = row.mResetName;
                ensure_equals("reset naming for " + ctrl,
                              reset, "rst_" + setting);
                const std::map<std::string, std::string>::const_iterator rb =
                    scan.mResets.find(reset);
                ensure("reset resolves in XML: " + reset,
                       rb != scan.mResets.end());
                ensure_equals("reset parameter for " + reset,
                              rb->second, setting);
            }

            // preset ownership matches the canonical lists
            ensure_equals("mPresetOwned for " + ctrl,
                          row.mPresetOwned, owned.count(setting) != 0);
            if (row.mPresetOwned) { ++owned_rows; }

            // enum ranges
            ensure("tool mask valid: " + ctrl,
                   row.mTool >= 1 && row.mTool <= AL_TOOL_BOTH);
            ensure("section valid: " + ctrl, row.mSection < (U32)AL_SEC_COUNT);
            ensure("tier valid: " + ctrl, row.mTier < (U32)AL_TIER_COUNT);

            // count bounds + zeroed spares [Codex delta-5 finding 3]
            ensure("clause count bound: " + ctrl,
                   row.mClauseCount <= AL_MAX_CLAUSES);
            ensure_equals("mClauseCount == 0 iff UNCONDITIONAL: " + ctrl,
                          row.mClauseCount == 0, row.mUnconditional);
            if (row.mUnconditional) { ++unconditional; }
            total_clauses += row.mClauseCount;

            for (S32 c = 0; c < AL_MAX_CLAUSES; ++c)
            {
                const ALDiopterClause& clause = row.mClauses[c];
                if (c >= row.mClauseCount)
                {
                    ensure("spare clause zeroed: " + ctrl,
                           clause.mTermCount == 0);
                }
                ensure("term count bound: " + ctrl,
                       clause.mTermCount <= AL_MAX_TERMS);
                for (S32 t = 0; t < AL_MAX_TERMS; ++t)
                {
                    const ALDiopterTerm& term = clause.mTerms[t];
                    if (t >= clause.mTermCount || c >= row.mClauseCount)
                    {
                        ensure("spare term zeroed: " + ctrl,
                               !term.mSetting && term.mMask == 0u &&
                               term.mPred == PRED_NONE && !term.mNegate);
                        continue;
                    }
                    if (term.mPred != PRED_NONE)
                    {
                        ensure("pred term carries no setting: " + ctrl,
                               !term.mSetting && term.mMask == 0u);
                        ensure("pred in range: " + ctrl,
                               term.mPred > PRED_NONE &&
                               term.mPred < AL_PRED_COUNT);
                    }
                    else
                    {
                        ensure("setting term named: " + ctrl,
                               term.mSetting != nullptr);
                        ensure("setting term mask nonempty: " + ctrl,
                               term.mMask != 0u);
                        ensure(std::string("term setting resolves: ") +
                               term.mSetting,
                               alDiopterStateValue(defaults,
                                                   term.mSetting) >= 0);
                    }
                }
            }
        }

        // whole-table invariants (DIOPTER_RELEVANCE_TABLE.md "Asserted
        // invariants")
        ensure_equals("all 181 settings covered exactly once",
                      (S32)seen_settings.size(), 181);
        for (const std::map<std::string, std::string>::value_type& b :
             scan.mBinding)
        {
            ensure("XML setting has a table row: " + b.second,
                   seen_settings.count(b.second) != 0);
        }
        ensure_equals("exactly one nullptr reset", null_resets, 1);
        ensure_equals("exactly one UNCONDITIONAL row", unconditional, 1);
        ensure_equals("93 preset-owned rows (44 diopter + 49 kaleido)",
                      owned_rows, 93);
        ensure_equals("194 explicit clauses", total_clauses, 194);
    }

    // Invariant W (design doc §4.2, §7 Phase 3 row): "in every supported
    // configuration ... the vertical scrollbar is not visible." Walks the
    // real XUI to compute each tab's worst-case content height (the
    // generator's own §3.3 same-rect overlay bands mean visiting every
    // sibling panel of a band -- not just the currently-visible one --
    // still yields the correct max; see maxBottomEdge()'s comment), then
    // asserts it fits the viewport the scroll_container would have AT
    // min_height, not merely at the floater's default size.
    template<> template<>
    void aldiopterrelevance_object::test<3>()
    {
        const std::string src = readFileOrFail(floaterXmlPath());

        std::string floater_tag;
        ensure("<floater> tag found", findOpenTagText(src, "floater", floater_tag));
        const S32 floater_h = attrInt(floater_tag, "height", -1);
        const S32 floater_min_h = attrInt(floater_tag, "min_height", -1);
        const S32 floater_min_w = attrInt(floater_tag, "min_width", -1);
        ensure("floater height authored", floater_h > 0);
        ensure("floater min_height authored", floater_min_h > 0);
        ensure_equals("min_width unchanged at 520 (hard constraint)", floater_min_w, 520);
        ensure("default height is never below the measured floor -- Invariant W "
               "must hold at the size the floater actually opens at, not just "
               "at some hypothetical larger size",
               floater_h >= floater_min_h);

        // follows="all" on tab_container/scroll_container and
        // follows="left|right|bottom" (no vertical stretch) on the footer
        // means 100% of any floater_h -> floater_min_h shrink is absorbed
        // by the tab_container/scroll_container chain -- so the viewport
        // AT min_height is exactly (authored viewport) minus that shrink.
        const S32 shrink = floater_h - floater_min_h;

        S32 worst_case_content = 0;
        for (S32 t = 0; t < AL_DIOPTER_TAB_COUNT; ++t)
        {
            const TabSpec& spec = DIOPTER_TABS[t];

            std::string scroll_tag;
            ensure(std::string("scroll_container found: ") + spec.mScrollContainer,
                   findTagByNameAttr(src, "scroll_container", spec.mScrollContainer, scroll_tag));
            const S32 scroll_h = attrInt(scroll_tag, "height", -1);
            const S32 scroll_w = attrInt(scroll_tag, "width", -1);
            ensure(std::string("scroll_container height authored: ") + spec.mScrollContainer,
                   scroll_h > 0);
            ensure(std::string("scroll_container width authored: ") + spec.mScrollContainer,
                   scroll_w > 0);

            // [F7] calcVisibleSize() inputs beyond raw width/height: the
            // border and the hide_scrollbar override.  These containers ship
            // with border_visible unset (default false, llscrollcontainer.cpp
            // Params) and getBorderWidth() returns 0 for an invisible border
            // (llscrollcontainer.cpp:821-828).  If someone turns the border
            // on, this mirror must learn its thickness -- fail loudly.
            std::string border_visible;
            ensure(std::string("scroll_container border must stay invisible "
                               "or this calcVisibleSize mirror needs its "
                               "thickness: ") + spec.mScrollContainer,
                   !(findAttr(scroll_tag, "border_visible", border_visible) &&
                     border_visible == "true"));
            const S32 border_width = 0;
            std::string hide_sb;
            const bool hide_scrollbar =
                findAttr(scroll_tag, "hide_scrollbar", hide_sb) &&
                hide_sb == "true";

            std::string inner_tag;
            ensure(std::string("inner panel found: ") + spec.mInnerPanel,
                   findTagByNameAttr(src, "panel", spec.mInnerPanel, inner_tag));
            const S32 authored_h = attrInt(inner_tag, "height", -1);
            const S32 authored_w = attrInt(inner_tag, "width", -1);
            ensure(std::string("inner panel height authored: ") + spec.mInnerPanel,
                   authored_h > 0);
            ensure(std::string("inner panel width authored: ") + spec.mInnerPanel,
                   authored_w > 0);

            std::string inner_body;
            ensure(std::string("inner panel span found: ") + spec.mInnerPanel,
                   findNamedPanelSpan(src, spec.mInnerPanel, inner_body));
            const S32 computed_h = maxBottomEdge(inner_body);

            // The authored number must not UNDER-state the real content --
            // this is what catches a control added straight to the XML
            // without re-running the generator that keeps the two in sync.
            ensure(llformat("%s (%s): authored height %d must cover the "
                            "computed content height %d", spec.mLabel,
                            spec.mInnerPanel, authored_h, computed_h),
                   authored_h >= computed_h);

            const S32 scroll_h_at_min = scroll_h - shrink;
            ensure(llformat("%s: viewport at min_height (%d) must be positive",
                            spec.mLabel, scroll_h_at_min),
                   scroll_h_at_min > 0);

            // [F7/CR2-10] THE invariant, as an EXACT statement-for-statement
            // mirror of LLScrollContainer::calcVisibleSize()
            // (llscrollcontainer.cpp:442-483) evaluated at the floater's
            // MINIMUM size -- not the (possibly larger) default.  The doc
            // rect is the inner panel's authored rect (getScrolledViewRect,
            // :444); the container rect height is the authored scroll height
            // minus the min-size shrink.  Correspondence, production line ->
            // here:
            //   :445-446 scrollbar_size = (mSize == -1 ? UIScrollbarSize
            //            : mSize)      -> the `size` attr / default below
            //   :452-453 visible = rect - 2*border      -> visible_* init
            //   :455-456 both flags start false         -> flag init
            //   :458     if (!mHideScrollbar)           -> if (!hide_scrollbar)
            //   :462-466 v-bar test (1 px tolerance), eats WIDTH
            //   :467-470 h-bar test (1 px tolerance), eats HEIGHT
            //   :476-480 second v-bar recomputation against the REDUCED
            //            height -- only when the first test said no
            // A visible vertical bar at min_height is exactly the hazard
            // section 4.2 exists to rule out; a visible horizontal bar would
            // shrink the height viewport and re-admit it.
            //
            // :445-446 -- the optional per-container size override: mSize is
            // the XUI `size` attribute (llscrollcontainer.cpp:79 Params
            // default -1), and -1 selects the UIScrollbarSize setting.
            const S32 size_attr = attrInt(scroll_tag, "size", -1);
            const S32 scrollbar_size =
                (size_attr == -1) ? uiScrollbarSizeDefault() : size_attr;
            S32 visible_width = scroll_w - 2 * border_width;        // :452
            S32 visible_height = scroll_h_at_min - 2 * border_width; // :453
            bool show_v_scrollbar = false;                          // :455
            bool show_h_scrollbar = false;                          // :456
            if (!hide_scrollbar)                                    // :458
            {
                if ((authored_h - visible_height) > 1)              // :462
                {
                    show_v_scrollbar = true;                        // :464
                    visible_width -= scrollbar_size;                // :465
                }
                if ((authored_w - visible_width) > 1)               // :467
                {
                    show_h_scrollbar = true;                        // :469
                    visible_height -= scrollbar_size;               // :470
                    if (!show_v_scrollbar &&
                        ((authored_h - visible_height) > 1))        // :476
                    {
                        show_v_scrollbar = true;                    // :478
                        visible_width -= scrollbar_size;            // :479
                    }
                }
            }
            ensure(llformat("Invariant W: %s content height %d vs %d px "
                            "viewport at min_height (borders %d) -- the "
                            "vertical scrollbar would be visible",
                            spec.mLabel, authored_h, visible_height,
                            border_width),
                   !show_v_scrollbar);
            ensure(llformat("Invariant W: %s content width %d vs %d px "
                            "visible width -- the horizontal scrollbar would "
                            "be visible (and would eat %d px of height)",
                            spec.mLabel, authored_w, visible_width,
                            scrollbar_size),
                   !show_h_scrollbar);

            worst_case_content = llmax(worst_case_content, computed_h);
        }

        LL_INFOS("UltimateDiopter") << "Invariant W: worst measured tab "
            "content height " << worst_case_content << "px; floater "
            "min_height " << floater_min_h << "px" << LL_ENDL;
    }
}
